server:
  port: 7073


spring:
  application:
    name: gateway


zuul:
  host:
    socket-timeout-millis: 6000
    connect-timeout-millis: 6000
  routes:
    application:
      service-id: application
      path: /application/**


